[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
optimizer = true
optimizer_runs = 1000
via_ir = true

remappings = [
    'light-account/=lib/light-account/src/',
    'modular-account/=lib/light-account/lib/modular-account/src/',
    'account-abstraction/=lib/light-account/lib/account-abstraction/contracts/',
    '@account-abstraction/contracts/=lib/light-account/lib/account-abstraction/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@ethereum-attestation-service/eas-contracts/contracts/=lib/eas-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    'forge-std/=lib/forge-std/src/',
]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
